version: '3.8'

services:
  fastapi-app:
    build: .
    
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - DATABASE_HOST=mongodb://mongo:27017/mydatabase:27017  # Adjust the database name as needed

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  mongo-tools:
    image: mongo:latest
    command: mongosh --host mongo
    depends_on:
      - mongo

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tiktok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  mongodb-data:
    driver: local
  postgres_data :
    driver: local
